# Generated by Django 2.2.5 on 2019-11-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cur_num', models.IntegerField()),
                ('max_num', models.IntegerField()),
                ('game_map', models.IntegerField()),
                ('player1', models.CharField(max_length=30)),
                ('player2', models.CharField(max_length=30)),
                ('player3', models.CharField(max_length=30)),
                ('player4', models.CharField(max_length=30)),
                ('ready2', models.IntegerField()),
                ('ready3', models.IntegerField()),
                ('ready4', models.IntegerField()),
                ('hasPassword', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('readyNum', models.IntegerField()),
            ],
        ),
    ]
